### ISSUE TITLE
Security Plus

### ISSUE THREAD

**Issue by highrez** [james-fray/Security-Plus#2]
I installed this Safari extension on two computers but on the third it didn't work. On a Google search page there would be no green circles next to the links. I uninstalled and reinstalled but that did not make a difference. How can I fix this?

**Comment by james-fray** [comment]
Can you submit an screenshot?

**Comment by highrez** [comment]
I finally got it to work. I had to drag it out of library/safari/extensions to the desk top, then double click it to reinstall and it finally worked that way. I'm not sure why that macbook was different from the others.
