### ISSUE TITLE
0.1.3 forces tab labels to display URLs instead of webpage titles

### ISSUE THREAD

**Issue by faustie** [james-fray/Security-Plus#3]
The new version of SP, 0.1.3, has an odd bug that shows up whenever I start Firefox (37.0.2) with the FF option "Show all my windows and tabs from last time" checked.  All the tabs get displayed momentarily with their titles, then a "connecting" message and throbbers appears on the tabs, after which the the titles are gone, and the URLs are displayed instead.

The behavior persists with all other addons disabled.

I assume this has something to do with the new version of SP forcing a page refresh.

**Comment by james-fray** [comment]
Seems like profile damage to me, can you confirm in a clean profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by faustie** [comment]
Yes, it happens with a perfectly clean profile.  FF 37.0.2.  Windows 7.

**Comment by james-fray** [comment]
How about version 0.1.4b1
https://addons.mozilla.org/firefox/downloads/file/323062/security_plus-0.1.4b1-fx.xpi?src=devhub
