### ISSUE TITLE
Make it possible to scan URLs that aren't hyperlinked

### ISSUE THREAD

**Issue by anonsubmitter** [james-fray/Security-Plus#5]
Can you update Security Plus so that it's possible to scan URLs that aren't hyperlinked?

**Comment by james-fray** [comment]
Thanks for the report. For Firefox, the context menu now appears on text-links as well. Unfortunately, this feature is not available on the Chrome version yet.

**Comment by anonsubmitter** [comment]
@james-fray Security Plus can no longer scan text links.
