### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by anonsubmitter** [james-fray/Security-Plus#8]
You use Google Analytics in Security Plus and Download Virus Checker. What info is collected by these add-ons and how is it used? Would it be possible to replace Google Analytics with a self-hosted Piwik installation?

**Comment by james-fray** [comment]
Google Analytics is used to find the total number of installations as well as the country codes.

Note that both FAQ pages support Do Not Track. If your Do Not Track is enabled you will get
```
Do Not Track is enabled -> We are not recoreding analytics per user request
```
in the console.
